<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property blob $image
 * @property string $hybridauth_provider_name
 * @property string $hybridauth_provider_uid
 * 
 * @method integer getId()                       Returns the current record's "id" value
 * @method string  getName()                     Returns the current record's "name" value
 * @method blob    getImage()                    Returns the current record's "image" value
 * @method string  getHybridauthProviderName()   Returns the current record's "hybridauth_provider_name" value
 * @method string  getHybridauthProviderUid()    Returns the current record's "hybridauth_provider_uid" value
 * @method User    setId()                       Sets the current record's "id" value
 * @method User    setName()                     Sets the current record's "name" value
 * @method User    setImage()                    Sets the current record's "image" value
 * @method User    setHybridauthProviderName()   Sets the current record's "hybridauth_provider_name" value
 * @method User    setHybridauthProviderUid()    Sets the current record's "hybridauth_provider_uid" value
 * 
 * @package    connect
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'comment' => 'ID',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'default' => 'no name',
             'comment' => 'ユーザー名',
             'length' => 255,
             ));
        $this->hasColumn('image', 'blob', null, array(
             'type' => 'blob',
             'notnull' => false,
             'comment' => 'アイコン画像',
             ));
        $this->hasColumn('hybridauth_provider_name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'comment' => 'HybridAuthプロバイダ',
             'length' => 20,
             ));
        $this->hasColumn('hybridauth_provider_uid', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'comment' => 'HybridAuthプロバイダUID',
             'length' => 255,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('comment', 'ユーザー');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}