<?php

/**
 * BaseVote_comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ita_id
 * @property string $comment
 * @property string $user
 * @property Vote_ita $Vote_ita
 * 
 * @method integer      getId()       Returns the current record's "id" value
 * @method integer      getItaId()    Returns the current record's "ita_id" value
 * @method string       getComment()  Returns the current record's "comment" value
 * @method string       getUser()     Returns the current record's "user" value
 * @method Vote_ita     getVoteIta()  Returns the current record's "Vote_ita" value
 * @method Vote_comment setId()       Sets the current record's "id" value
 * @method Vote_comment setItaId()    Sets the current record's "ita_id" value
 * @method Vote_comment setComment()  Sets the current record's "comment" value
 * @method Vote_comment setUser()     Sets the current record's "user" value
 * @method Vote_comment setVoteIta()  Sets the current record's "Vote_ita" value
 * 
 * @package    connect
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVote_comment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote_comment');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('ita_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('user', 'string', 65, array(
             'type' => 'string',
             'default' => '',
             'length' => 65,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vote_ita', array(
             'local' => 'ita_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'owningSide' => true));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}