<?php

/**
 * BaseAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_name
 * @property string $show_name
 * @property string $password
 * @property string $address
 * @property varchar $email
 * @property integer $twitter
 * @property integer $mixi
 * @property integer $facebook
 * @property integer $google
 * @property timestamp $last_login
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getUserName()   Returns the current record's "user_name" value
 * @method string    getShowName()   Returns the current record's "show_name" value
 * @method string    getPassword()   Returns the current record's "password" value
 * @method string    getAddress()    Returns the current record's "address" value
 * @method varchar   getEmail()      Returns the current record's "email" value
 * @method integer   getTwitter()    Returns the current record's "twitter" value
 * @method integer   getMixi()       Returns the current record's "mixi" value
 * @method integer   getFacebook()   Returns the current record's "facebook" value
 * @method integer   getGoogle()     Returns the current record's "google" value
 * @method timestamp getLastLogin()  Returns the current record's "last_login" value
 * @method Account   setId()         Sets the current record's "id" value
 * @method Account   setUserName()   Sets the current record's "user_name" value
 * @method Account   setShowName()   Sets the current record's "show_name" value
 * @method Account   setPassword()   Sets the current record's "password" value
 * @method Account   setAddress()    Sets the current record's "address" value
 * @method Account   setEmail()      Sets the current record's "email" value
 * @method Account   setTwitter()    Sets the current record's "twitter" value
 * @method Account   setMixi()       Sets the current record's "mixi" value
 * @method Account   setFacebook()   Sets the current record's "facebook" value
 * @method Account   setGoogle()     Sets the current record's "google" value
 * @method Account   setLastLogin()  Sets the current record's "last_login" value
 * 
 * @package    connect
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('user_name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 20,
             ));
        $this->hasColumn('show_name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 20,
             ));
        $this->hasColumn('password', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 20,
             ));
        $this->hasColumn('address', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('email', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
        $this->hasColumn('twitter', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mixi', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('facebook', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('google', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}