<?php

/**
 * BaseVote_ita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property Vote_shop $Vote_shop
 * @property Vote_comment $Vote_comment
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method string       getTitle()        Returns the current record's "title" value
 * @method string       getDescription()  Returns the current record's "description" value
 * @method Vote_shop    getVoteShop()     Returns the current record's "Vote_shop" value
 * @method Vote_comment getVoteComment()  Returns the current record's "Vote_comment" value
 * @method Vote_ita     setId()           Sets the current record's "id" value
 * @method Vote_ita     setTitle()        Sets the current record's "title" value
 * @method Vote_ita     setDescription()  Sets the current record's "description" value
 * @method Vote_ita     setVoteShop()     Sets the current record's "Vote_shop" value
 * @method Vote_ita     setVoteComment()  Sets the current record's "Vote_comment" value
 * 
 * @package    connect
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVote_ita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote_ita');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vote_shop', array(
             'local' => 'id',
             'foreign' => 'ita_id'));

        $this->hasOne('Vote_comment', array(
             'local' => 'id',
             'foreign' => 'ita_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}