<?php

/**
 * BaseVote_shop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ita_id
 * @property string $url
 * @property integer $votes
 * 
 * @method integer   getId()     Returns the current record's "id" value
 * @method integer   getItaId()  Returns the current record's "ita_id" value
 * @method string    getUrl()    Returns the current record's "url" value
 * @method integer   getVotes()  Returns the current record's "votes" value
 * @method Vote_shop setId()     Sets the current record's "id" value
 * @method Vote_shop setItaId()  Sets the current record's "ita_id" value
 * @method Vote_shop setUrl()    Sets the current record's "url" value
 * @method Vote_shop setVotes()  Sets the current record's "votes" value
 * 
 * @package    connect
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVote_shop extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote_shop');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('ita_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('votes', 'integer', null, array(
             'type' => 'integer',
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}