<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/07 02:32:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jimoto',
  'username' => 'jimoto_user',
  'password' => 'jimoto2501',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_unicode_ci',
  ),
  'name' => 'doctrine',
)),);
