<?php

/**
 * Vote_shopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Vote_shopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Vote_shopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vote_shop');
    }
    
    public function getTargetThreads($ita_id) {
    
    $q = $this->createQuery('t')
            ->where('t.ita_id = ?', $ita_id);
    
    return $q->execute();
  }
}