<?php

/**
 * Vote_commentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Vote_commentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Vote_commentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vote_comment');
    }
}