<?php

/**
 * Vote_itaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Vote_itaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Vote_itaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vote_ita');
    }
}