# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

homepage:
  url:   /
  param: { module: Page, action: Show, slug: top }

page_show:
  url:   /page/:slug
  param: { module: Page, action: Show }

#login:
#  url:   /login
#  param: { module: login, action: index }
  
vote:
  url:   /vote
  param: { module: vote, action: index }

setting:
  url:   /setting
  param: { module: setting, action: index }
  
personal:
  url:   /personal
  param: { module: Page, action: Show }
  
link:
  url:   /personal
  param: { module: Page, action: Show }

distance:
  url:   /distance
  param: { module: distance, action: index }
  
login_endpoint:
  url:   /login/endpoint
  param: { module: auth, action: endPoint }
  
login:
  url:   /login
  param: { module: auth, action: index }

logout:
  url:   /logout
  param: { module: auth, action: logout }

login_provider:
  url:   /login/:provider
  param: { module: auth, action: slogin }
  requirements:
    provider: Facebook|Google|Twitter
  
default:
  url:   /:module/:action/*