# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

homepage:
  url:   /
  param: { module: Page, action: index, slug: top }

page_show:
  url:   /page/:slug
  param: { module: Page, action: index }

#login:
#  url:   /login
#  param: { module: login, action: index }

vote_ita:
  url:   /vote_ita
  param: { module: vote_ita, action: index }

vote_ita_new:
  url:   /vote_ita/new
  param: { module: vote_ita, action: new }

vote_ita_edit:
  url:   /vote_ita/edit
  param: { module: vote_ita, action: edit }

vote_ita_new:
  url:   /vote_ita/delete
  param: { module: vote, action: delete } 
  
vote_shop:
  url:   /vote_shop
  param: { module: vote, action: index }

vote_shop_new:
  url:   /vote_shop/new
  param: { module: vote, action: new }

vote_shop_votes:
  url:   /vote_shop/votes
  param: { module: vote, action: votes }
  
vote_shop_delete:
  url:   /vote_shop/delete
  param: { module: vote, action: delete }

setting:
  url:   /setting
  param: { module: setting, action: index }
  
setting_edit:
  url:   /setting/edit
  param: { module: setting, action: edit }

classmate:
  url:   /classmate
  param: { module: classmate, action: index }
  
personal:
  url:   /personal
  param: { module: personal, action: index }
  
link:
  url:   /link
  param: { module: Page, action: Show }

distance:
  url:   /distance
  param: { module: distance, action: index }
  
login_endpoint:
  url:   /login/endpoint
  param: { module: auth, action: endPoint }
  
login:
  url:   /login
  param: { module: auth, action: index }

logout:
  url:   /logout
  param: { module: auth, action: logout }

login_provider:
  url:   /login/:provider
  param: { module: auth, action: slogin }
  requirements:
    provider: Facebook|Google|Twitter
  
default:
  url:   /:module/:action/*