# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
#      dsn:      mysql:host=localhost;dbname=jimoto
#      dsn:      mysql:host=127.0.0.1;dbname=dephx8n35mq
      dsn:      mysql:host=mysqlsdb.co8hm2var4k9.eu-west-1.rds.amazonaws.com;port=3306;dbname=dephx8n35mq
#      username: root
#      password: sasagawa2501
      username: dephx8n35mq
      password: YtJxRSO0E&as
      attributes:
        default_table_charset: utf8
        default_table_collate: utf8_unicode_ci
