<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/08/20 12:25:09
$this->security = array (
  'slogin' => 
  array (
    'is_secure' => false,
  ),
  'endpoint' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
