<?php
// auto-generated by sfEnvironmentYamlConfigHandler
// date: 2012/08/20 12:25:11
return array (
  'base_url' => 'http://127.0.0.1/frontend_dev.php/login/endpoint',
  'providers' => 
  array (
    'OpenID' => 
    array (
      'enabled' => true,
    ),
    'Yahoo' => 
    array (
      'enabled' => true,
    ),
    'AOL' => 
    array (
      'enabled' => true,
    ),
    'Google' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'id' => '',
        'secret' => '',
      ),
      'scope' => '',
    ),
    'Facebook' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'id' => '	274692389303731',
        'secret' => 'e2aaae94075531bc0d7e39f4631e5557',
      ),
      'scope' => '',
      'display' => '',
    ),
    'Twitter' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'key' => 'x9XkTLYVMlKN8YWb0hA',
        'secret' => 'icXsZgQ0lkXDce95edO90Nxb7zCjRfxTjHWy0DNFXQ',
      ),
    ),
    'Live' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'id' => '',
        'secret' => '',
      ),
    ),
    'MySpace' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'key' => '',
        'secret' => '',
      ),
    ),
    'LinkedIn' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'key' => '',
        'secret' => '',
      ),
    ),
    'Foursquare' => 
    array (
      'enabled' => true,
      'keys' => 
      array (
        'id' => '',
        'secret' => '',
      ),
    ),
  ),
  'debug_mode' => false,
  'debug_file' => '',
);
