Vote_ita:
  actAs:
    Timestampable: ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type:     string(100)
      notnull:  true
    description:
      type:     string(500)

Vote_shop:
  actAs:
    Timestampable: ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    ita_id:
      type: integer
      notnull:  true
      default:  ''
    url:    
      type: string(255)
      default:  ''
    name:    
      type: string(255)
      default:  ''
    address:    
      type: string(255)
      default:  ''
    votes:
      type: integer
      default:  ''
  relations:
    Vote_ita:
      class: Vote_ita
      foreignAlias: Vote_shop
      foreignType: one
      onDelete: CASCADE
      type: one
      local: ita_id
      foreign: id
      owningSide: true
      
Vote_comment:
  actAs:
    Timestampable: ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    ita_id:
      type: integer
      notnull:  true
      default:  ''
    comment:    
      type: string(255)
      default:  ''
    user:
      type: string(65)
      default:  ''
  relations:
    Vote_ita:
      class: Vote_ita
      foreignAlias: Vote_comment
      foreignType: one
      onDelete: CASCADE
      type: one
      local: ita_id
      foreign: id
      owningSide: true
      
User:
  actAs: { Timestampable: ~ }
#  tableName: users
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
    comment: 'ユーザー'
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      autoincrement: true
      comment: 'ID'
    name:
      type: string(255)
      fixed: false
      notnull: true
      default: 'no name'
      comment: 'ユーザー名'
    image:
      type: blob
      notnull: false
      comment: 'アイコン画像'
    address: string(200)
    email: varchar(100)
    twitter: integer
    mixi: integer
    facebook: integer
    google: integer
    last_login: timestamp
    hybridauth_provider_name:
      type: string(20)
      fixed: false
      notnull: true
      comment: 'HybridAuthプロバイダ'
    hybridauth_provider_uid:
      type: string(255)
      fixed: false
      notnull: true
      comment: 'HybridAuthプロバイダUID'