Page:
  actAs:
    Timestampable: ~
    Sluggable: ~
  columns:
    title:
      type:     string(100)
      notnull:  true
      default:  ''
    body:
      type:     clob
      notnull:  true
      default:  ''
    category:
      type:     string(32)
      notnull:  true
      default:  ''

Account:
  actAs:
    Timestampable: ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    user_name:
      type:     string(20)
      notnull:  true
      default:  ''
    show_name:
      type:     string(20)
      notnull:  true
      default:  ''
    password:
      type:     string(20)
      notnull:  true
      default:  ''
    address: string(200)
    email: varchar(100)
    twitter: integer
    mixi: integer
    facebook: integer
    google: integer
    last_login: timestamp
      
Vote_ita:
  actAs:
    Timestampable: ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type:     string(100)
      notnull:  true
      
Vote_shop:
  actAs:
    Timestampable: ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    ita_id:
      type: integer
      notnull:  true
      default:  ''
    url:    
      type: string(255)
      default:  ''
    votes:
      type: integer
      default:  ''
      
User:
  actAs: { Timestampable: ~ }
  tableName: users
  options:
    type: MyISAM
    collate: utf8_unicode_ci
    charset: utf8
    comment: 'ユーザー'
  columns:
    id:
      type: integer(4)
      unsigned: false
      primary: true
      autoincrement: true
      comment: 'ID'
    name:
      type: string(255)
      fixed: false
      notnull: true
      default: 'no name'
      comment: 'ユーザー名'
    image:
      type: blob
      notnull: false
      comment: 'アイコン画像'
    hybridauth_provider_name:
      type: string(20)
      fixed: false
      notnull: true
      comment: 'HybridAuthプロバイダ'
    hybridauth_provider_uid:
      type: string(255)
      fixed: false
      notnull: true
      comment: 'HybridAuthプロバイダUID'